### ISSUE TITLE
Solutions for Current and Following 2 days available via inspect element

### ISSUE THREAD

**Issue by TheVanadium** [pavo-etc/minecraftle#25]
![image](https://github.com/pavo-etc/minecraftle/assets/53013571/76ab4b51-3aa6-430b-ae44-ad4b8781cbd4)
This is relatively insecure. Is there a way to hide this, and could we at least reduce the solutions to the current day only?

On an related note, using a date and solution attribute is not really HTML-friendly, so we should try refactoring it.

**Comment by pavo-etc** [comment]
Currently the puzzle is generated on the server based on the current date in the server's location.  This means that the puzzle only changes when midnight passes in the server's location. This is a problem over multiple timezones as the puzzle may not change at my midnight.  At certain times it is possible for there to be 3 different dates happening simultaneously (timezones are fucked up).  This is why there are 3 days being passed in the HTML, since the server has no good way of knowing which of the 3 possible days the user is actually in.

I would generate the solution client side but JavaScript has no way to seed its Math.random() function, so I can't use that.  Would need to use a library for generating random numbers that can take a seed, or write our own functions for it.  Didn't wanna bother with that so just made the solution server rendered.

I'm not sure what you mean by HTML-friendly, this is a fairly elegant (though hacky) solution to this problem.  If someone is willing to cheat and inspect element then there is basically nothing we can do to hide the solution from them.  We could encode the solution text so its not in plaintext, but if a user is bringing up developer tools then they could force a win anyone using the JS console.

**Comment by pavo-etc** [comment]
I am rewriting the whole app in React.  The new version will have the random puzzle selected client side and will resolve this issue

**Comment by pavo-etc** [comment]
See #31
